### ISSUE TITLE
How to run lit-element in Chrome which has no customElements?

### ISSUE THREAD

**Issue by Electronification** [Polymer/lit-html#335]
I have built an web app which includes elements defined by Polymer 1.0 and Lit-element.
It works well in Chrome browser (Version 61.0.3163.79), but lit elements doesn't work in Chrome that doesn't support customElements.

I have tried to add webcomponents-loader.js, and load lit elements on WebComponentsReady fired.
I can find customElements in console panel like below:
R {X: false, h: Qc, aa: Map, I: false, Z: Array[0]…}

but lit elements was not interpreted that has no shadow root and has no children.

Do I need to load more polyfills for this case?

**Comment by Electronification** [comment]
`lit-element.js:89 Uncaught TypeError: this.attachShadow is not a function(…)_createRoot @ lit-element.js:89ready @ lit-element.js:69ready @ iq-plugin-loader.js:53_enableProperties @ properties-changed.js:315connectedCallback @ properties-mixin.js:203connectedCallback @ connect-mixin.js:33u.connectedCallback @ CustomElementInternals.js:303y @ CustomElementInternals.js:86(anonymous function) @ Node.js:81(anonymous function) @ VM8158:1`

**Comment by LarsDenBakker** [comment]
Be careful, you are telling it to use the v0 shadow dom spec which is incompatible with v1. I guess it should just load the v1 polyfill.

**Comment by web-padawan** [comment]
Polymer 1.0 would be anyways incompatible with the Shady render feature, since it does not expose the `ShadyCSS` API, so mixing those does not look viable for use in production to me.

**Comment by justinfagnani** [comment]
Seems like this issue should be opened on the lit-element repo, but lit-html. lit-html itself has nothing much to do with custom elements.
