### ISSUE TITLE
[@lit-labs/signals] export `SignalWatcherApi` type

### ISSUE THREAD

**Issue by malobre** [Polymer/lit-html#5192]
### Which package(s) are affected?

Other/unknown (please mention in description)

### Description

`@lit-labs/signals@0.2.0`

When extending `SignalWatcher`, typescripts throws an error because `SignalWatcherApi` isn't exported:
```
error TS4020: 'extends' clause of exported class 'MyElement' has or is using private name 'SignalWatcherApi'.
```

### Reproduction

https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbwDLBgUQDYFMRYHYwC+cAZlBCHAOQapUDcAUKJLIgMrADmeAhhgHVeMAMYALLFGJkKcAEQABWjAC0GXgCMAzgHot3Phi1ymjLAA9W8Eeq1a4ncNgDiULFhjA8XOBZj4AE3tOHn4hUQkoAAoUdGxcAgBKREIgA

### Workaround

I have not found a workaround

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

Failing in @lit-labs/signals@0.2.0, interface did not exist before

### Browser/OS/Node environment

node 25.2.1
npm 11.6.4
tsc 5.9.3
linux 6.17.9

**Comment by sorvell** [comment]
We aren't seeing this issue in the tests, and I think the reason may be that our tsconfig is using `"target": "es2021",
    "module": "NodeNext",`.

If that works, perhaps it's a workaround until this is fixed.

**Comment by malobre** [comment]
Tried the options you suggested, unfortunately it doesn't seem to make a difference.

**Comment by aomarks** [comment]
✋ I am also seeing this error with target = es2021 or es2022, and module = nodenext after upgrading from 0.1.3 to 0.2.0

tsc logs: https://github.com/breadboard-ai/breadboard/actions/runs/21518216974/job/62001970794?pr=7635
