### ISSUE TITLE
lit html 0.11.4 doesnt work with TS >= 3.1.1 because of duplicate identifiers

### ISSUE THREAD

**Issue by mzeiher** [Polymer/lit-html#524]
lit html declares the CustomElementRegistry class in template-instance.ts
declare global {
    class CustomElementRegistry {
        upgrade(node: Node): void;
    }
}

tsc also declares this class in 3.1.1 in lib.dom.d.ts so TSC throws a TS2300 Error
`error TS2300: Duplicate identifier 'CustomElementRegistry'.`
maybe remove the declaration and update to TSC => 3.1.1?

**Comment by ValLisetsky** [comment]
Just got the same issue. I was forced to upgrade to 3.1 typescript because of new "unknown" types used in lit-element. Now i stuck with duplicate `CustomElementRegistry` because its defined in TypeScript `lib.dom`. Please fix as it makes `lit-element` and `lit-html` not usable with TypeScript 3.x

**Comment by merlinnot** [comment]
We might consider using `typesVersions` for backwards compatibility.
